export interface BookEntry {
  id: string; title: string; author: string; dynasty: string;
  category: string; brief: string; chapterCount: number; excerpt: string;
}

export const BOOKS: BookEntry[] = [
  {
    id: "chenshu",
    title: "陈书",
    author: "佚名",
    dynasty: "唐",
    category: "史部",
    brief: "姚思廉撰，纪传体南朝陈史",
    chapterCount: 2,
    excerpt: "高祖上",
  },
  {
    id: "chuci",
    title: "楚辞",
    author: "屈原等",
    dynasty: "战国",
    category: "集部",
    brief: "屈原宋玉等楚地诗歌总集",
    chapterCount: 17,
    excerpt: "帝高阳之苗裔兮，朕皇考曰伯庸。\n摄提贞于孟陬兮，惟庚寅吾以降。\n皇览揆余初度兮，肇锡余以嘉名：\n名余曰正则兮，字余曰灵均。\n纷吾既有此内美兮，又重之以修能。\n扈江离与辟芷兮，纫秋兰以为佩。\n汩余若将不…",
  },
  {
    id: "dongjingmenghualu",
    title: "东京梦华录",
    author: "佚名",
    dynasty: "宋",
    category: "笔记",
    brief: "孟元老著，北宋汴京风情画卷",
    chapterCount: 10,
    excerpt: "",
  },
  {
    id: "fushengliuji",
    title: "浮生六记",
    author: "佚名",
    dynasty: "清",
    category: "笔记",
    brief: "沈复著，与芸娘的烟霞知己之书",
    chapterCount: 4,
    excerpt: "余幼聘金沙于氏，八龄而夭。娶陈氏。陈名芸，字淑珍，舅氏心余先生女也，生而颖慧，学语时，口授《琵琶行》，即能成诵。四龄失怙，母金氏，弟克昌，家徒壁立。芸既长，娴女红，三口仰其十指供给，克昌从师，修脯无缺…",
  },
  {
    id: "gongsunlongzi",
    title: "公孙龙子",
    author: "佚名",
    dynasty: "战国",
    category: "子部",
    brief: "名家代表，白马非子命题",
    chapterCount: 6,
    excerpt: "龙于孔穿会赵平原君家。穿曰：“素闻先生高谊，愿为弟子久，但不取先生 以白马为非马耳！请去此术，则穿请为弟子。”",
  },
  {
    id: "guahuapinlu",
    title: "古画品录",
    author: "谢赫",
    dynasty: "南朝",
    category: "艺术",
    brief: "中国第一部绘画品评专著，六法论",
    chapterCount: 7,
    excerpt: "",
  },
  {
    id: "guanzi",
    title: "管子",
    author: "佚名",
    dynasty: "春秋-战国",
    category: "子部",
    brief: "托名管仲，杂家思想集成",
    chapterCount: 74,
    excerpt: "凡有地牧民者，务在四时，守在仓廪。国多财，则远者来，地辟举，则民留处；仓廪实，则知礼节；衣食足，则知荣辱；上服度，则六亲固。四维张，则君令行。故省刑之要，在禁文巧，守国之度，在饰四维，顺民之经，在明鬼…",
  },
  {
    id: "gushishijiu",
    title: "古诗十九首",
    author: "佚名",
    dynasty: "东汉",
    category: "集部",
    brief: "南朝萧统辑录，五言诗艺术典范",
    chapterCount: 19,
    excerpt: "",
  },
  {
    id: "hanfeizi",
    title: "韩非子",
    author: "韩非",
    dynasty: "战国",
    category: "子部",
    brief: "法家集大成之作",
    chapterCount: 55,
    excerpt: "臣闻：天下阴燕阳魏，连荆固齐，收韩而成从，将西面以与秦强为难。臣窃笑之。世有三亡，而天下得之，其此之谓乎！臣闻之曰：“以乱攻治者亡，以邪攻正者亡，以逆攻顺者亡”。今天下之府库不盈，囷仓空虚，悉其士民，…",
  },
  {
    id: "hanshu",
    title: "汉书",
    author: "佚名",
    dynasty: "东汉",
    category: "史部",
    brief: "班固著，第一部断代史",
    chapterCount: 9,
    excerpt: "高祖，沛丰邑中阳里人也，姓刘氏。母媪尝息大泽之陂，梦与神遇。是时雷电晦冥，父太公往视，则见交龙于上。已而有娠，遂产高祖。",
  },
  {
    id: "jingkangchuanxinlu",
    title: "靖康传信录",
    author: "佚名",
    dynasty: "宋",
    category: "笔记",
    brief: "李纲著，靖康之变亲历记",
    chapterCount: 2,
    excerpt: "",
  },
  {
    id: "jinshu",
    title: "晋书",
    author: "佚名",
    dynasty: "唐",
    category: "史部",
    brief: "房玄龄等撰，纪传体晋代史",
    chapterCount: 8,
    excerpt: "宣皇帝讳懿，字仲达，河内温县孝敬里人，姓司马氏。其先出自帝高阳之子重黎，为夏官祝融，历唐、虞、夏、商，世序其职。及周，以夏官为司马。其后程柏休父，周宣王时，以世官克平徐方，锡以官族，因而为氏。楚汉间，…",
  },
  {
    id: "liezi",
    title: "列子",
    author: "佚名",
    dynasty: "战国",
    category: "子部",
    brief: "道家经典，列御寇思想的传本",
    chapterCount: 8,
    excerpt: "子列子曰：“昔者圣人因阴阳以统天地。夫有形者生于无形，则天地安从生？故曰：有太易，有太初，有太始，有太素。太易者，未见气也：太初者，气之始也；太始者，形之始也；太素者，质之始也。气形质具而未相离，故曰…",
  },
  {
    id: "liji",
    title: "礼记",
    author: "佚名",
    dynasty: "春秋-西汉",
    category: "经部",
    brief: "儒家礼学论文集，与周礼仪礼合称三礼",
    chapterCount: 49,
    excerpt: "敖不可长，欲不可从，志不可满，乐不可极。",
  },
  {
    id: "lunheng",
    title: "论衡",
    author: "王充",
    dynasty: "东汉",
    category: "子部",
    brief: "唯物主义哲学论著，疾虚妄",
    chapterCount: 30,
    excerpt: "操行有常贤，仕宦无常遇。贤不贤，才也；遇不遇，时也。才高行洁，不可保以必尊贵；能薄操浊，不可保以必卑贱。或高才洁行，不遇退在下流；薄能浊操，遇，在众上。世各自有以取士，士亦各自得以进。进在遇，退在不遇…",
  },
  {
    id: "mingjibeilue",
    title: "明季北略",
    author: "佚名",
    dynasty: "清",
    category: "笔记",
    brief: "计六奇著，明末北方史事",
    chapterCount: 65,
    excerpt: "附记：康熙三年孟夏四日，先君子曰：予壮年时有华道士云：江右张真人北都建醮，伏坛久之，见天上诸神俱不在，惟关圣一人守天门而已。真人问诸神安在？圣曰：今新天子出世，诸神下界拥护矣。真人曰：圣何不往？圣曰：…",
  },
  {
    id: "mingjinanlue",
    title: "明季南略",
    author: "佚名",
    dynasty: "清",
    category: "笔记",
    brief: "计六奇著，明末南方史事",
    chapterCount: 19,
    excerpt: "岁辛亥仲夏，予编“南略”一书；始于甲申五月、止于康熙乙巳，凡二十余年事，分十八卷。虽叙次不伦、见闻各异，而笔之所至，雅俗兼收，有明之微绪余烬，皆毕于是矣。嗟嗟！祸乱之作，天之所以开皇清也；岂人力欤！爰…",
  },
  {
    id: "mingshi",
    title: "明史",
    author: "佚名",
    dynasty: "清",
    category: "史部",
    brief: "张廷玉等撰，纪传体明代史",
    chapterCount: 27,
    excerpt: "◎太祖一",
  },
  {
    id: "pingsonglu",
    title: "平宋录",
    author: "佚名",
    dynasty: "元",
    category: "笔记",
    brief: "刘敏中著，元灭南宋之记录",
    chapterCount: 3,
    excerpt: "至元十一年甲戌正月，上命右丞相巴延节制诸军伐宋。七月，巴延陛辞，上谕之曰：“古之善取江南者，唯曹彬一人。汝能不杀，是亦曹彬也。”",
  },
  {
    id: "qijingshisanpian",
    title: "棋经十三篇",
    author: "佚名",
    dynasty: "宋",
    category: "艺术",
    brief: "张拟著，古代围棋理论经典",
    chapterCount: 13,
    excerpt: "",
  },
  {
    id: "shiji",
    title: "史记",
    author: "佚名",
    dynasty: "西汉",
    category: "史部",
    brief: "司马迁著，纪传体开山之作",
    chapterCount: 118,
    excerpt: "东至于海，登丸山，及岱宗。西至于空桐，登鸡头。南至于江，登熊、湘。北逐荤粥，合符釜山，而邑于涿鹿之阿。迁徙往来无常处，以师兵为营卫。官名皆以云命，为云师。置左右大监，监于万国。万国和，而鬼神山川封禅与…",
  },
  {
    id: "shuijingzhu",
    title: "水经注",
    author: "佚名",
    dynasty: "北魏",
    category: "史部",
    brief: "郦道元著，水经注释与地理风俗志",
    chapterCount: 40,
    excerpt: "去嵩高五万里，地之中也。",
  },
  {
    id: "songmojiwen",
    title: "松漠纪闻",
    author: "佚名",
    dynasty: "宋",
    category: "笔记",
    brief: "洪皓著，金国见闻与北方风物",
    chapterCount: 3,
    excerpt: "女真酋长乃新罗人，号完颜氏。完颜犹汉言“王”也。女真以其练事，后随以首领让之。兄弟三人，一为熟女真酋长，号万户。其一适他国。完颜年六十余，女真妻之以女亦六十余。生二子，其长即胡来也。自此传三人，至杨哥…",
  },
  {
    id: "songshi",
    title: "宋史",
    author: "佚名",
    dynasty: "元",
    category: "史部",
    brief: "脱脱等撰，纪传体宋代史",
    chapterCount: 6,
    excerpt: "○太祖一",
  },
  {
    id: "suiyuanshidan",
    title: "随园食单",
    author: "佚名",
    dynasty: "清",
    category: "笔记",
    brief: "袁枚著，古代美食文化经典",
    chapterCount: 14,
    excerpt: "余雅慕此旨，每食于某氏而饱，必使家厨往彼灶觚，执弟子之礼。四十年来，颇集众美。有学就者，有十分中得六七者，有仅得二三者，亦有竟失传者。余都问其方略，集而存之。虽不甚省记，亦载某家某味，以志景行。自觉好…",
  },
  {
    id: "taoanmengyi",
    title: "陶庵梦忆",
    author: "佚名",
    dynasty: "明",
    category: "笔记",
    brief: "张岱著，明末士人生活剪影",
    chapterCount: 9,
    excerpt: "陶庵国破家亡，无所归止，披发入山，駴駴为野人。故旧见之，如毒药猛兽，愕窒不敢与接。作自挽诗，每欲引决。因《石匮书》未成，尚视息人世。然瓶粟屡罄，不能举火，始知首阳二老直头饿死，不食周粟，还是后人妆点语…",
  },
  {
    id: "tiangongkaiwu",
    title: "天工开物",
    author: "宋应星",
    dynasty: "明",
    category: "科技",
    brief: "明代农业手工业技术百科",
    chapterCount: 3,
    excerpt: "宋子曰：上古神农氏若存若亡，然味其徽号，两言至今存矣。生人不能久生而五谷生之，五谷不能自生而生人生之。土脉历时代而异，种性随水土而分。不然，神农去陶唐，粒食已千年矣。耒耜之利，以教天下，岂有隐焉。而纷…",
  },
  {
    id: "wenxindiaolong",
    title: "文心雕龙",
    author: "刘勰",
    dynasty: "南朝",
    category: "集部",
    brief: "中国古代文学理论巨著",
    chapterCount: 50,
    excerpt: "傍及万品，动植皆文∶龙凤以藻绘呈瑞，虎豹以炳蔚凝姿；云霞雕色，有逾画工之妙；草木贲华，无待锦匠之奇。夫岂外饰，盖自然耳。至于林籁结响，调如竽瑟；泉石激韵，和若球锽：故形立则章成矣，声发则文生矣。夫以无…",
  },
  {
    id: "xunzi",
    title: "荀子",
    author: "荀况",
    dynasty: "战国",
    category: "子部",
    brief: "儒家荀学，性恶论与礼法并重",
    chapterCount: 32,
    excerpt: "吾尝终日而思矣，不如须臾之所学也。吾尝跂而望矣，不如登高之博见也。登高而招，臂非加长也，而见者远；顺风而呼，声非加疾也，而闻者彰。假舆马者，非利足也，而致千里；假舟楫者，非能水也，而绝江河。君子生非异…",
  },
  {
    id: "yili",
    title: "仪礼",
    author: "佚名",
    dynasty: "春秋",
    category: "经部",
    brief: "儒家礼学十七篇，详述冠婚丧祭仪节",
    chapterCount: 17,
    excerpt: "主人戒宾。宾礼辞，许。主人再拜，宾答拜。主人退，宾拜送。",
  },
  {
    id: "yizhoushu",
    title: "逸周书",
    author: "佚名",
    dynasty: "战国",
    category: "经部",
    brief: "周代文献汇编，诰誓训典之属",
    chapterCount: 11,
    excerpt: "天生民而制其度，度小大以整，权轻重以极，明本末以立中。立中以补损，补损以知足。爵以明等极，极以正民，正中外以成命。正上下以顺政。自迩弥兴自远，远迩备极终也。明王是以敬微而顺分，分次以知和，知和以知乐，…",
  },
  {
    id: "zhuangzi",
    title: "庄子",
    author: "庄周",
    dynasty: "战国",
    category: "子部",
    brief: "道家核心经典，汪洋恣肆的寓言之作",
    chapterCount: 3,
    excerpt: "北冥有鱼，其名为鲲。鲲之大，不知其几千里也。化而为鸟，其名为鹏。鹏之背，不知其几千里也。怒而飞，其翼若垂天之云。是鸟也，海运则将徙于南冥。南冥者，天池也。",
  },
  {
    id: "zuozhuan",
    title: "左传",
    author: "佚名",
    dynasty: "春秋",
    category: "经部",
    brief: "春秋三传之一，详于记事",
    chapterCount: 12,
    excerpt: "隐公元年",
  },
];

export function findBook(id: string): BookEntry | undefined {
  return BOOKS.find((b) => b.id === id);
}
