/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DialogueRouteImport } from './routes/dialogue'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DialogueIndexRouteImport } from './routes/dialogue.index'
import { Route as DialogueHistoryRouteImport } from './routes/dialogue.history'
import { Route as DialogueIdRouteImport } from './routes/dialogue.$id'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as ApiDialogueRouteImport } from './routes/api/dialogue'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogueRoute = DialogueRouteImport.update({
  id: '/dialogue',
  path: '/dialogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogueIndexRoute = DialogueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DialogueRoute,
} as any)
const DialogueHistoryRoute = DialogueHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DialogueRoute,
} as any)
const DialogueIdRoute = DialogueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DialogueRoute,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDialogueRoute = ApiDialogueRouteImport.update({
  id: '/api/dialogue',
  path: '/api/dialogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/create': typeof CreateRoute
  '/dialogue': typeof DialogueRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/api/dialogue': typeof ApiDialogueRoute
  '/article/$id': typeof ArticleIdRoute
  '/dialogue/$id': typeof DialogueIdRoute
  '/dialogue/history': typeof DialogueHistoryRoute
  '/dialogue/': typeof DialogueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/create': typeof CreateRoute
  '/gallery': typeof GalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/api/dialogue': typeof ApiDialogueRoute
  '/article/$id': typeof ArticleIdRoute
  '/dialogue/$id': typeof DialogueIdRoute
  '/dialogue/history': typeof DialogueHistoryRoute
  '/dialogue': typeof DialogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/create': typeof CreateRoute
  '/dialogue': typeof DialogueRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/api/dialogue': typeof ApiDialogueRoute
  '/article/$id': typeof ArticleIdRoute
  '/dialogue/$id': typeof DialogueIdRoute
  '/dialogue/history': typeof DialogueHistoryRoute
  '/dialogue/': typeof DialogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/community'
    | '/create'
    | '/dialogue'
    | '/gallery'
    | '/onboarding'
    | '/profile'
    | '/api/chat'
    | '/api/dialogue'
    | '/article/$id'
    | '/dialogue/$id'
    | '/dialogue/history'
    | '/dialogue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/community'
    | '/create'
    | '/gallery'
    | '/onboarding'
    | '/profile'
    | '/api/chat'
    | '/api/dialogue'
    | '/article/$id'
    | '/dialogue/$id'
    | '/dialogue/history'
    | '/dialogue'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/community'
    | '/create'
    | '/dialogue'
    | '/gallery'
    | '/onboarding'
    | '/profile'
    | '/api/chat'
    | '/api/dialogue'
    | '/article/$id'
    | '/dialogue/$id'
    | '/dialogue/history'
    | '/dialogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRoute
  CreateRoute: typeof CreateRoute
  DialogueRoute: typeof DialogueRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDialogueRoute: typeof ApiDialogueRoute
  ArticleIdRoute: typeof ArticleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogue': {
      id: '/dialogue'
      path: '/dialogue'
      fullPath: '/dialogue'
      preLoaderRoute: typeof DialogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogue/': {
      id: '/dialogue/'
      path: '/'
      fullPath: '/dialogue/'
      preLoaderRoute: typeof DialogueIndexRouteImport
      parentRoute: typeof DialogueRoute
    }
    '/dialogue/history': {
      id: '/dialogue/history'
      path: '/history'
      fullPath: '/dialogue/history'
      preLoaderRoute: typeof DialogueHistoryRouteImport
      parentRoute: typeof DialogueRoute
    }
    '/dialogue/$id': {
      id: '/dialogue/$id'
      path: '/$id'
      fullPath: '/dialogue/$id'
      preLoaderRoute: typeof DialogueIdRouteImport
      parentRoute: typeof DialogueRoute
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dialogue': {
      id: '/api/dialogue'
      path: '/api/dialogue'
      fullPath: '/api/dialogue'
      preLoaderRoute: typeof ApiDialogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DialogueRouteChildren {
  DialogueIdRoute: typeof DialogueIdRoute
  DialogueHistoryRoute: typeof DialogueHistoryRoute
  DialogueIndexRoute: typeof DialogueIndexRoute
}

const DialogueRouteChildren: DialogueRouteChildren = {
  DialogueIdRoute: DialogueIdRoute,
  DialogueHistoryRoute: DialogueHistoryRoute,
  DialogueIndexRoute: DialogueIndexRoute,
}

const DialogueRouteWithChildren = DialogueRoute._addFileChildren(
  DialogueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRoute,
  CreateRoute: CreateRoute,
  DialogueRoute: DialogueRouteWithChildren,
  GalleryRoute: GalleryRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDialogueRoute: ApiDialogueRoute,
  ArticleIdRoute: ArticleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
