/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QaSquareRouteImport } from './routes/qa-square'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DialogueRouteImport } from './routes/dialogue'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnotationsRouteImport } from './routes/annotations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DialogueIndexRouteImport } from './routes/dialogue.index'
import { Route as TongyouCommunityRouteImport } from './routes/tongyou/community'
import { Route as TongyouChallengeRouteImport } from './routes/tongyou/challenge'
import { Route as DialogueHistoryRouteImport } from './routes/dialogue.history'
import { Route as DialogueIdRouteImport } from './routes/dialogue.$id'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as ApiTextToImageRouteImport } from './routes/api/text-to-image'
import { Route as ApiSearchImageRouteImport } from './routes/api/search-image'
import { Route as ApiKnowledgeAiFillRouteImport } from './routes/api/knowledge-ai-fill'
import { Route as ApiDialogueRouteImport } from './routes/api/dialogue'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiArticlesRouteImport } from './routes/api/articles'
import { Route as ApiAncientBooksRouteImport } from './routes/api/ancient-books'
import { Route as TongyouCommunityIdRouteImport } from './routes/tongyou/community.$id'
import { Route as ApiArticlesTagsRouteImport } from './routes/api/articles/tags'
import { Route as ApiArticlesStatsRouteImport } from './routes/api/articles/stats'
import { Route as ApiArticlesRecommendationsRouteImport } from './routes/api/articles/recommendations'
import { Route as ApiArticlesCategoriesRouteImport } from './routes/api/articles/categories'
import { Route as ApiArticlesIdRouteImport } from './routes/api/articles/$id'
import { Route as ApiArticlesIdRelationsRouteImport } from './routes/api/articles/$id/relations'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QaSquareRoute = QaSquareRouteImport.update({
  id: '/qa-square',
  path: '/qa-square',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogueRoute = DialogueRouteImport.update({
  id: '/dialogue',
  path: '/dialogue',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotationsRoute = AnnotationsRouteImport.update({
  id: '/annotations',
  path: '/annotations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogueIndexRoute = DialogueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DialogueRoute,
} as any)
const TongyouCommunityRoute = TongyouCommunityRouteImport.update({
  id: '/tongyou/community',
  path: '/tongyou/community',
  getParentRoute: () => rootRouteImport,
} as any)
const TongyouChallengeRoute = TongyouChallengeRouteImport.update({
  id: '/tongyou/challenge',
  path: '/tongyou/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogueHistoryRoute = DialogueHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DialogueRoute,
} as any)
const DialogueIdRoute = DialogueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DialogueRoute,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTextToImageRoute = ApiTextToImageRouteImport.update({
  id: '/api/text-to-image',
  path: '/api/text-to-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchImageRoute = ApiSearchImageRouteImport.update({
  id: '/api/search-image',
  path: '/api/search-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeAiFillRoute = ApiKnowledgeAiFillRouteImport.update({
  id: '/api/knowledge-ai-fill',
  path: '/api/knowledge-ai-fill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDialogueRoute = ApiDialogueRouteImport.update({
  id: '/api/dialogue',
  path: '/api/dialogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArticlesRoute = ApiArticlesRouteImport.update({
  id: '/api/articles',
  path: '/api/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAncientBooksRoute = ApiAncientBooksRouteImport.update({
  id: '/api/ancient-books',
  path: '/api/ancient-books',
  getParentRoute: () => rootRouteImport,
} as any)
const TongyouCommunityIdRoute = TongyouCommunityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TongyouCommunityRoute,
} as any)
const ApiArticlesTagsRoute = ApiArticlesTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => ApiArticlesRoute,
} as any)
const ApiArticlesStatsRoute = ApiArticlesStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ApiArticlesRoute,
} as any)
const ApiArticlesRecommendationsRoute =
  ApiArticlesRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => ApiArticlesRoute,
  } as any)
const ApiArticlesCategoriesRoute = ApiArticlesCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ApiArticlesRoute,
} as any)
const ApiArticlesIdRoute = ApiArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiArticlesRoute,
} as any)
const ApiArticlesIdRelationsRoute = ApiArticlesIdRelationsRouteImport.update({
  id: '/relations',
  path: '/relations',
  getParentRoute: () => ApiArticlesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annotations': typeof AnnotationsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/dialogue': typeof DialogueRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/gallery': typeof GalleryRoute
  '/heritage': typeof HeritageRoute
  '/journey': typeof JourneyRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/qa-square': typeof QaSquareRoute
  '/search': typeof SearchRoute
  '/api/ancient-books': typeof ApiAncientBooksRoute
  '/api/articles': typeof ApiArticlesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/dialogue': typeof ApiDialogueRoute
  '/api/knowledge-ai-fill': typeof ApiKnowledgeAiFillRoute
  '/api/search-image': typeof ApiSearchImageRoute
  '/api/text-to-image': typeof ApiTextToImageRoute
  '/article/$id': typeof ArticleIdRoute
  '/dialogue/$id': typeof DialogueIdRoute
  '/dialogue/history': typeof DialogueHistoryRoute
  '/tongyou/challenge': typeof TongyouChallengeRoute
  '/tongyou/community': typeof TongyouCommunityRouteWithChildren
  '/dialogue/': typeof DialogueIndexRoute
  '/api/articles/$id': typeof ApiArticlesIdRouteWithChildren
  '/api/articles/categories': typeof ApiArticlesCategoriesRoute
  '/api/articles/recommendations': typeof ApiArticlesRecommendationsRoute
  '/api/articles/stats': typeof ApiArticlesStatsRoute
  '/api/articles/tags': typeof ApiArticlesTagsRoute
  '/tongyou/community/$id': typeof TongyouCommunityIdRoute
  '/api/articles/$id/relations': typeof ApiArticlesIdRelationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annotations': typeof AnnotationsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/gallery': typeof GalleryRoute
  '/heritage': typeof HeritageRoute
  '/journey': typeof JourneyRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/qa-square': typeof QaSquareRoute
  '/search': typeof SearchRoute
  '/api/ancient-books': typeof ApiAncientBooksRoute
  '/api/articles': typeof ApiArticlesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/dialogue': typeof ApiDialogueRoute
  '/api/knowledge-ai-fill': typeof ApiKnowledgeAiFillRoute
  '/api/search-image': typeof ApiSearchImageRoute
  '/api/text-to-image': typeof ApiTextToImageRoute
  '/article/$id': typeof ArticleIdRoute
  '/dialogue/$id': typeof DialogueIdRoute
  '/dialogue/history': typeof DialogueHistoryRoute
  '/tongyou/challenge': typeof TongyouChallengeRoute
  '/tongyou/community': typeof TongyouCommunityRouteWithChildren
  '/dialogue': typeof DialogueIndexRoute
  '/api/articles/$id': typeof ApiArticlesIdRouteWithChildren
  '/api/articles/categories': typeof ApiArticlesCategoriesRoute
  '/api/articles/recommendations': typeof ApiArticlesRecommendationsRoute
  '/api/articles/stats': typeof ApiArticlesStatsRoute
  '/api/articles/tags': typeof ApiArticlesTagsRoute
  '/tongyou/community/$id': typeof TongyouCommunityIdRoute
  '/api/articles/$id/relations': typeof ApiArticlesIdRelationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annotations': typeof AnnotationsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/dialogue': typeof DialogueRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/gallery': typeof GalleryRoute
  '/heritage': typeof HeritageRoute
  '/journey': typeof JourneyRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/qa-square': typeof QaSquareRoute
  '/search': typeof SearchRoute
  '/api/ancient-books': typeof ApiAncientBooksRoute
  '/api/articles': typeof ApiArticlesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/dialogue': typeof ApiDialogueRoute
  '/api/knowledge-ai-fill': typeof ApiKnowledgeAiFillRoute
  '/api/search-image': typeof ApiSearchImageRoute
  '/api/text-to-image': typeof ApiTextToImageRoute
  '/article/$id': typeof ArticleIdRoute
  '/dialogue/$id': typeof DialogueIdRoute
  '/dialogue/history': typeof DialogueHistoryRoute
  '/tongyou/challenge': typeof TongyouChallengeRoute
  '/tongyou/community': typeof TongyouCommunityRouteWithChildren
  '/dialogue/': typeof DialogueIndexRoute
  '/api/articles/$id': typeof ApiArticlesIdRouteWithChildren
  '/api/articles/categories': typeof ApiArticlesCategoriesRoute
  '/api/articles/recommendations': typeof ApiArticlesRecommendationsRoute
  '/api/articles/stats': typeof ApiArticlesStatsRoute
  '/api/articles/tags': typeof ApiArticlesTagsRoute
  '/tongyou/community/$id': typeof TongyouCommunityIdRoute
  '/api/articles/$id/relations': typeof ApiArticlesIdRelationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annotations'
    | '/auth'
    | '/chat'
    | '/create'
    | '/dashboard'
    | '/dialogue'
    | '/favorites'
    | '/gallery'
    | '/heritage'
    | '/journey'
    | '/onboarding'
    | '/profile'
    | '/qa-square'
    | '/search'
    | '/api/ancient-books'
    | '/api/articles'
    | '/api/chat'
    | '/api/dialogue'
    | '/api/knowledge-ai-fill'
    | '/api/search-image'
    | '/api/text-to-image'
    | '/article/$id'
    | '/dialogue/$id'
    | '/dialogue/history'
    | '/tongyou/challenge'
    | '/tongyou/community'
    | '/dialogue/'
    | '/api/articles/$id'
    | '/api/articles/categories'
    | '/api/articles/recommendations'
    | '/api/articles/stats'
    | '/api/articles/tags'
    | '/tongyou/community/$id'
    | '/api/articles/$id/relations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annotations'
    | '/auth'
    | '/chat'
    | '/create'
    | '/dashboard'
    | '/favorites'
    | '/gallery'
    | '/heritage'
    | '/journey'
    | '/onboarding'
    | '/profile'
    | '/qa-square'
    | '/search'
    | '/api/ancient-books'
    | '/api/articles'
    | '/api/chat'
    | '/api/dialogue'
    | '/api/knowledge-ai-fill'
    | '/api/search-image'
    | '/api/text-to-image'
    | '/article/$id'
    | '/dialogue/$id'
    | '/dialogue/history'
    | '/tongyou/challenge'
    | '/tongyou/community'
    | '/dialogue'
    | '/api/articles/$id'
    | '/api/articles/categories'
    | '/api/articles/recommendations'
    | '/api/articles/stats'
    | '/api/articles/tags'
    | '/tongyou/community/$id'
    | '/api/articles/$id/relations'
  id:
    | '__root__'
    | '/'
    | '/annotations'
    | '/auth'
    | '/chat'
    | '/create'
    | '/dashboard'
    | '/dialogue'
    | '/favorites'
    | '/gallery'
    | '/heritage'
    | '/journey'
    | '/onboarding'
    | '/profile'
    | '/qa-square'
    | '/search'
    | '/api/ancient-books'
    | '/api/articles'
    | '/api/chat'
    | '/api/dialogue'
    | '/api/knowledge-ai-fill'
    | '/api/search-image'
    | '/api/text-to-image'
    | '/article/$id'
    | '/dialogue/$id'
    | '/dialogue/history'
    | '/tongyou/challenge'
    | '/tongyou/community'
    | '/dialogue/'
    | '/api/articles/$id'
    | '/api/articles/categories'
    | '/api/articles/recommendations'
    | '/api/articles/stats'
    | '/api/articles/tags'
    | '/tongyou/community/$id'
    | '/api/articles/$id/relations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnotationsRoute: typeof AnnotationsRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  DialogueRoute: typeof DialogueRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  GalleryRoute: typeof GalleryRoute
  HeritageRoute: typeof HeritageRoute
  JourneyRoute: typeof JourneyRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  QaSquareRoute: typeof QaSquareRoute
  SearchRoute: typeof SearchRoute
  ApiAncientBooksRoute: typeof ApiAncientBooksRoute
  ApiArticlesRoute: typeof ApiArticlesRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiDialogueRoute: typeof ApiDialogueRoute
  ApiKnowledgeAiFillRoute: typeof ApiKnowledgeAiFillRoute
  ApiSearchImageRoute: typeof ApiSearchImageRoute
  ApiTextToImageRoute: typeof ApiTextToImageRoute
  ArticleIdRoute: typeof ArticleIdRoute
  TongyouChallengeRoute: typeof TongyouChallengeRoute
  TongyouCommunityRoute: typeof TongyouCommunityRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-square': {
      id: '/qa-square'
      path: '/qa-square'
      fullPath: '/qa-square'
      preLoaderRoute: typeof QaSquareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogue': {
      id: '/dialogue'
      path: '/dialogue'
      fullPath: '/dialogue'
      preLoaderRoute: typeof DialogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotations': {
      id: '/annotations'
      path: '/annotations'
      fullPath: '/annotations'
      preLoaderRoute: typeof AnnotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogue/': {
      id: '/dialogue/'
      path: '/'
      fullPath: '/dialogue/'
      preLoaderRoute: typeof DialogueIndexRouteImport
      parentRoute: typeof DialogueRoute
    }
    '/tongyou/community': {
      id: '/tongyou/community'
      path: '/tongyou/community'
      fullPath: '/tongyou/community'
      preLoaderRoute: typeof TongyouCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tongyou/challenge': {
      id: '/tongyou/challenge'
      path: '/tongyou/challenge'
      fullPath: '/tongyou/challenge'
      preLoaderRoute: typeof TongyouChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogue/history': {
      id: '/dialogue/history'
      path: '/history'
      fullPath: '/dialogue/history'
      preLoaderRoute: typeof DialogueHistoryRouteImport
      parentRoute: typeof DialogueRoute
    }
    '/dialogue/$id': {
      id: '/dialogue/$id'
      path: '/$id'
      fullPath: '/dialogue/$id'
      preLoaderRoute: typeof DialogueIdRouteImport
      parentRoute: typeof DialogueRoute
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/text-to-image': {
      id: '/api/text-to-image'
      path: '/api/text-to-image'
      fullPath: '/api/text-to-image'
      preLoaderRoute: typeof ApiTextToImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search-image': {
      id: '/api/search-image'
      path: '/api/search-image'
      fullPath: '/api/search-image'
      preLoaderRoute: typeof ApiSearchImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge-ai-fill': {
      id: '/api/knowledge-ai-fill'
      path: '/api/knowledge-ai-fill'
      fullPath: '/api/knowledge-ai-fill'
      preLoaderRoute: typeof ApiKnowledgeAiFillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dialogue': {
      id: '/api/dialogue'
      path: '/api/dialogue'
      fullPath: '/api/dialogue'
      preLoaderRoute: typeof ApiDialogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/articles': {
      id: '/api/articles'
      path: '/api/articles'
      fullPath: '/api/articles'
      preLoaderRoute: typeof ApiArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ancient-books': {
      id: '/api/ancient-books'
      path: '/api/ancient-books'
      fullPath: '/api/ancient-books'
      preLoaderRoute: typeof ApiAncientBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tongyou/community/$id': {
      id: '/tongyou/community/$id'
      path: '/$id'
      fullPath: '/tongyou/community/$id'
      preLoaderRoute: typeof TongyouCommunityIdRouteImport
      parentRoute: typeof TongyouCommunityRoute
    }
    '/api/articles/tags': {
      id: '/api/articles/tags'
      path: '/tags'
      fullPath: '/api/articles/tags'
      preLoaderRoute: typeof ApiArticlesTagsRouteImport
      parentRoute: typeof ApiArticlesRoute
    }
    '/api/articles/stats': {
      id: '/api/articles/stats'
      path: '/stats'
      fullPath: '/api/articles/stats'
      preLoaderRoute: typeof ApiArticlesStatsRouteImport
      parentRoute: typeof ApiArticlesRoute
    }
    '/api/articles/recommendations': {
      id: '/api/articles/recommendations'
      path: '/recommendations'
      fullPath: '/api/articles/recommendations'
      preLoaderRoute: typeof ApiArticlesRecommendationsRouteImport
      parentRoute: typeof ApiArticlesRoute
    }
    '/api/articles/categories': {
      id: '/api/articles/categories'
      path: '/categories'
      fullPath: '/api/articles/categories'
      preLoaderRoute: typeof ApiArticlesCategoriesRouteImport
      parentRoute: typeof ApiArticlesRoute
    }
    '/api/articles/$id': {
      id: '/api/articles/$id'
      path: '/$id'
      fullPath: '/api/articles/$id'
      preLoaderRoute: typeof ApiArticlesIdRouteImport
      parentRoute: typeof ApiArticlesRoute
    }
    '/api/articles/$id/relations': {
      id: '/api/articles/$id/relations'
      path: '/relations'
      fullPath: '/api/articles/$id/relations'
      preLoaderRoute: typeof ApiArticlesIdRelationsRouteImport
      parentRoute: typeof ApiArticlesIdRoute
    }
  }
}

interface DialogueRouteChildren {
  DialogueIdRoute: typeof DialogueIdRoute
  DialogueHistoryRoute: typeof DialogueHistoryRoute
  DialogueIndexRoute: typeof DialogueIndexRoute
}

const DialogueRouteChildren: DialogueRouteChildren = {
  DialogueIdRoute: DialogueIdRoute,
  DialogueHistoryRoute: DialogueHistoryRoute,
  DialogueIndexRoute: DialogueIndexRoute,
}

const DialogueRouteWithChildren = DialogueRoute._addFileChildren(
  DialogueRouteChildren,
)

interface ApiArticlesIdRouteChildren {
  ApiArticlesIdRelationsRoute: typeof ApiArticlesIdRelationsRoute
}

const ApiArticlesIdRouteChildren: ApiArticlesIdRouteChildren = {
  ApiArticlesIdRelationsRoute: ApiArticlesIdRelationsRoute,
}

const ApiArticlesIdRouteWithChildren = ApiArticlesIdRoute._addFileChildren(
  ApiArticlesIdRouteChildren,
)

interface ApiArticlesRouteChildren {
  ApiArticlesIdRoute: typeof ApiArticlesIdRouteWithChildren
  ApiArticlesCategoriesRoute: typeof ApiArticlesCategoriesRoute
  ApiArticlesRecommendationsRoute: typeof ApiArticlesRecommendationsRoute
  ApiArticlesStatsRoute: typeof ApiArticlesStatsRoute
  ApiArticlesTagsRoute: typeof ApiArticlesTagsRoute
}

const ApiArticlesRouteChildren: ApiArticlesRouteChildren = {
  ApiArticlesIdRoute: ApiArticlesIdRouteWithChildren,
  ApiArticlesCategoriesRoute: ApiArticlesCategoriesRoute,
  ApiArticlesRecommendationsRoute: ApiArticlesRecommendationsRoute,
  ApiArticlesStatsRoute: ApiArticlesStatsRoute,
  ApiArticlesTagsRoute: ApiArticlesTagsRoute,
}

const ApiArticlesRouteWithChildren = ApiArticlesRoute._addFileChildren(
  ApiArticlesRouteChildren,
)

interface TongyouCommunityRouteChildren {
  TongyouCommunityIdRoute: typeof TongyouCommunityIdRoute
}

const TongyouCommunityRouteChildren: TongyouCommunityRouteChildren = {
  TongyouCommunityIdRoute: TongyouCommunityIdRoute,
}

const TongyouCommunityRouteWithChildren =
  TongyouCommunityRoute._addFileChildren(TongyouCommunityRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnotationsRoute: AnnotationsRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  DialogueRoute: DialogueRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  GalleryRoute: GalleryRoute,
  HeritageRoute: HeritageRoute,
  JourneyRoute: JourneyRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  QaSquareRoute: QaSquareRoute,
  SearchRoute: SearchRoute,
  ApiAncientBooksRoute: ApiAncientBooksRoute,
  ApiArticlesRoute: ApiArticlesRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiDialogueRoute: ApiDialogueRoute,
  ApiKnowledgeAiFillRoute: ApiKnowledgeAiFillRoute,
  ApiSearchImageRoute: ApiSearchImageRoute,
  ApiTextToImageRoute: ApiTextToImageRoute,
  ArticleIdRoute: ArticleIdRoute,
  TongyouChallengeRoute: TongyouChallengeRoute,
  TongyouCommunityRoute: TongyouCommunityRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
