// MINIMAL VERIFICATION: bypass TanStack Start entirely.
// If the user can see "It works!" on Vercel, the function runtime is fine
// and the bug is in the SSR chain. If they still get 500, the issue is
// at a deeper level (build output / Vercel config / runtime mismatch).

export default {
  async fetch(request: Request, _env: unknown, _ctx: unknown) {
    const requestId = Math.random().toString(36).slice(2, 8);
    const now = new Date().toISOString();
    const url = new URL(request.url);
    console.error(
      `[MINIMAL ${requestId}] incoming ${request.method} ${url.pathname}${url.search}`,
    );
    const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Vercel function works</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      body { font: 15px/1.5 system-ui, -apple-system, sans-serif; background: #fafafa; color: #111; display: grid; place-items: center; min-height: 100vh; margin: 0; padding: 1.5rem; }
      .card { max-width: 32rem; width: 100%; padding: 2rem; background: #fff; border: 1px solid #e5e7eb; border-radius: 0.5rem; }
      h1 { font-size: 1.25rem; margin: 0 0 0.5rem; }
      p { color: #4b5563; margin: 0.5rem 0; font-family: ui-monospace, monospace; font-size: 13px; }
      .ok { color: #047857; font-weight: 600; }
    </style>
  </head>
  <body>
    <div class="card">
      <h1 class="ok">It works! Vercel function is running.</h1>
      <p>request-id: <strong>${requestId}</strong></p>
      <p>time: <strong>${now}</strong></p>
      <p>method: <strong>${request.method}</strong></p>
      <p>path: <strong>${url.pathname}${url.search}</strong></p>
      <p style="margin-top:1rem">This response is generated by <code>src/server.ts</code> directly, completely bypassing the TanStack Start SSR chain. If you can read this, Vercel's function runtime, Nitro build output, and the deployment pipeline are all healthy. The next step is to find which part of the SSR chain is broken on Vercel (but not locally).</p>
    </div>
  </body>
</html>`;
    return new Response(html, {
      status: 200,
      headers: { "content-type": "text/html; charset=utf-8" },
    });
  },
};
